### ISSUE TITLE
Superpowered SDK for low latency?

### ISSUE THREAD

**Issue by meta-meta** [libpd/pd-for-android#12]
Have you guys looked into what it would take to plug libpd into the superpowered sdk?
http://superpowered.com/

**Comment by rpattabi** [comment]
superpowered says it does not add additional latency (towards the end of http://superpowered.com/androidaudiopathlatency/). Android's latency issue is not addressed by superpowered.

So, could you explain why would you want libpd integrated with superpowered?

**Comment by meta-meta** [comment]
They don't make it entirely clear what they are offering but imply some side-stepping of Android OS's inherent latency at a low level -- or I could be reading into it. I was wondering if the libpd team was aware of it and if it would allow for lower latency. It's unclear to me where Superpowered sits in the stack.

I only read through their site. Haven't done any testing with it.

**Comment by rpattabi** [comment]
I don't think Superpowered was able to side step Android's latency problem. I see they are trying their best to have this problem addressed ASAP (the article, publishing latency results for different devices). They just convey that their library does not add _additional_ latency.

Btw, I am also curious to know about what you ask libpd team here.

**Comment by tkirshboim** [comment]
Hi! Here is a link to a recent presentation by the Android audio team where they go into details regarding recent developments on latency in Android:
[Developing Android Apps with High Performance Audio, JUCE Summit 2015](https://www.youtube.com/watch?v=vPc7zvfpUos)

With this I'm closing this issue because issues on this repository are for bugs or suggestions for improvements in pd-for-android functionality and documentation, not so much for general discussions on Android audio. Nevertheless - thanks for getting involved! :+1:
