### ISSUE TITLE
Support pd patch encryption

### ISSUE THREAD

**Issue by rpattabi** [libpd/pd-for-android#51]
I may sound paranoid. But I think it may be important that pd-for-android provide support for pd patch encryption. At the moment it is too easy to lift the patches. This is fine in the spirit of pure data's openness and the ability to learn from other's work. However, there are too many copy-cat apps on play store sometimes even imitating app name and logos. It is definitely an issue when using pd-for-android. (Not sure if this is an issue in the way iOS apps are developed with libpd.)

Apps encrypting patch file and decrypting prior to passing pd-for-android is not effective as the patch is simply visible from the file system. pd-for-android may be able to a better job for this. I wonder if it can do encryption during the compilation, decrypt at runtime, etc. Note, I am a novice on the topic of cryptography. I only understand the issue apps will have using pd-for-android.

I would just like to get the discussion started on this topic.

**Comment by tkirshboim** [comment]
Hi @rpattabi ,
I understand your concern, however this out of scope for this project. Encryption of app resources is a general Android development related issue and not specific to libpd.

In any case, if you're interested in the topic, I'd suggest searching or posting at the [AndroidDev subreddit](https://www.reddit.com/r/androiddev), since that's a great place to ask these kind of general Android development related questions and get good answers. I can also recommend this talk on this topic where some tools that could solve what you're asking for are shown:
https://www.youtube.com/watch?v=vLU92bNeIdI

Also, in case of copyright infringement on the Play Store, there is the option to to ask Google to [take down the copy-cat app](https://support.google.com/legal/troubleshooter/1114905). 

Hope this helps!

**Comment by rpattabi** [comment]
@tkirshboim thanks for the pointers. 

I still feel, this suggestion is completely within the scope of Pd for Android. I agree encryption is general concern, but as a lib Pd for Android attempts to make things easy when dealing with Pd patches. Every commercial app developed using Pd for Android will have this requirement. 

For example, Pd for Android could encrypt the patch at compile time, and decrypt at runtime. If this makes sense, this may be considered as feature request.

**Comment by nettoyeurny** [comment]
I'm always happy to see commercial apps based on libpd, but I'm reluctant to commit any resources to a feature whose sole purpose is to address commercial concerns (and which may well be a burden on the overall project). Keep in mind that you're asking volunteers to implement, document, and maintain this. (And if someone were to send us a pull request, we'd still have to review and maintain it.)

Besides, there is a way to implement this outside of pd-for-android in a way that should address all your concerns: A Pd patch file is just a list of Pd messages. You could package an encrypted version of your patch with your app, then decrypt it on the fly and process one line at a time using libpd's message passing API; no need to write out the decrypted file. This could easily be packaged as a separate utility library.

PS: Out of curiosity, are there any known cases of Pd-for-Android apps that were actually ripped off down to the patch level?

**Comment by rpattabi** [comment]
@nettoyeurny thanks for the interesting approach

> are there any known cases of pd-for-android apps that were actually ripped off down to the patch level?

I know of no such case. It is only my imagination that the visibility of pd patch playing deterrant for commercial audio apps to use pd-for-android/libpd.

**Comment by nettoyeurny** [comment]
Let's close this issue, then. If you end up implementing the solution I outlined, please consider releasing it as a utility library.

If I may editorialize for a minute, though, I think you'd be better off focusing your efforts on making the best app you can instead of implementing anti-piracy measures that address a hypothetical threat. Most apps just sink without a trace. If you do get ripped off, that means that your app is one of the few that people are interested in. I for one was very happy when my book showed up on torrent sites. Tim O'Reilly was correct when he wrote that piracy is progressive taxation: http://www.openp2p.com/lpt/a/3015
